package tech.joaovitor.ws.providers;

import java.util.Map;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
public class JsonWebTokenProviderTest {
    @Autowired
    private TokenProvider tokenProvider;

    @Test
    void test() {
        Map<String, String> decoded = tokenProvider.decode("eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlV0ZjBDdVM4WUZVS2dGTEctMnlmLSJ9.eyJnaXZlbl9uYW1lIjoiSm_Do28gVml0b3IiLCJmYW1pbHlfbmFtZSI6IkNvc3RhIEZlcnJlaXJhIiwibmlja25hbWUiOiJqb2Fvdml0b3JjZmRldiIsIm5hbWUiOiJKb8OjbyBWaXRvciBDb3N0YSBGZXJyZWlyYSIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NKcDh5b0VYTDFpN0tLY25xOVRjaDNaQXhaTmUtd1o5djMwODcxTTNZRHFBODlvekxvPXM5Ni1jIiwibG9jYWxlIjoicHQtQlIiLCJ1cGRhdGVkX2F0IjoiMjAyNC0wNC0xNFQxNzo0OToxNS4zODhaIiwiZW1haWwiOiJqb2Fvdml0b3JjZmRldkBnbWFpbC5jb20iLCJlbWFpbF92ZXJpZmllZCI6dHJ1ZSwiaXNzIjoiaHR0cHM6Ly9kZXYtZ3NiaHVvanN1MWx6cXhkby51cy5hdXRoMC5jb20vIiwiYXVkIjoiOXJNS2J4OVhXcWRjRlNwb2x5ZUZRY2huekZNUzBzQTYiLCJpYXQiOjE3MTMxMTY5NTYsImV4cCI6MTcxMzE1Mjk1Niwic3ViIjoiZ29vZ2xlLW9hdXRoMnwxMDI3NjE0NTc2MDU4NTczMzc0MTkiLCJzaWQiOiJGWEl6N2YtLU9uYnZKejRUS0tXU1NGcERBLWx6MjMzbSIsIm5vbmNlIjoiYWpKNVNWQjBURGhaWmkxd2NYSjZUR3ByVG14eVUyMHVmbk5qUWtsdlQzVktNRzgxVmtzeFkybzBOUT09In0.CQO2sW64HXjEv7aFirr53JC5ZxAtKqXryTbHSyP5Zotw0ThEftu5lqrJ8M1yMng6HPXf2xhspuCHUikM7ku4L8Y1ELYdwSpF4FlkVA3eB7cOHlLkeYJAUvof5lEz9PzhmD02EpJA0N7DGl0eVfsb3BK_sx_kI5j5O9iGKOvddzZtkHhNdcuxw3_dCqhF2n8WnjsMxQPocpSy7WSDnLmZQB4Y5xaFGdpx6TUuK6rHqeduY0kSbdJYCzZEGGmayBCn4AIZMCraHGnUSJuqGlxeeym0ebQ6XJpKUTNQoXAOh7gRANtTpHrQDS3pFoxL-fRKL6NYD7Yn6KJP_ZHrMdCz9Q");
        System.out.println(decoded);
    }
}
